baseURL = "https://fancytom.com/"
languageCode = "en-us"
title = "Fancy Tom"
theme = "sketchaday"

[taxonomies]
  category = "categories"
  medium = "mediums"
  tag = "tags"
  series = "series"

[params]
  cloudinaryUserId = "dodzkb914"
  defaultImageWidth = "500"
  fullImageWidth = "1000"
  description = "Passion and craft. Build the library. Distort the signal. Process over product. Human hands. Make art not content."

[author]
  name = "Fancy Tom"
  email = "fancytom@example.com"

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = "assets/notwatching/hugo_stats\\.json"
    target = "css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    disableWatch = true
    source = "hugo_stats.json"
    target = "assets/notwatching/hugo_stats.json"
