baseURL = "https://fancytom.com/"
languageCode = "en-us"
title = "Fancy Tom"
theme = "fancytom"
description = "Portfolio website of artist extraordinaire Fancy Tom"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  medium = "mediums"

[params]
  cloudinaryUserId = "dodzkb914"
  defaultImageWidth = "500"
  fullImageWidth = "1000"