[context.deploy-preview.environment]
  HUGO_VERSION = "0.157.0"

[context.production.environment]
  HUGO_VERSION = "0.157.0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "all, noai, noimageai"